from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('public_portal/', views.public_portal_view, name='public_portal'),
    path('api/validate-team-secret/', views.validate_team_secret_view, name='validate_team_secret'),
    path('admin_dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('settings/', views.settings_view, name='settings'),
    path('draft/create/', views.create_draft_view, name='create_draft'),
    path('draft/edit/', views.edit_draft_view, name='edit_draft'),
    path('draft/run/', views.run_draft_view, name='run_draft'),
    path('draft/available-players/', views.available_players_view, name='available_players'),
    path('draft/make-pick/', views.make_pick_view, name='make_pick'),
    path('draft/undraft-pick/', views.undraft_pick_view, name='undraft_pick'),
    path('draft/validate-assignment/', views.validate_draft_assignment_view, name='validate_draft_assignment'),
    path('draft/reset/', views.reset_draft_view, name='reset_draft'),
    path('draft/assign-players/', views.assign_players_to_teams_view, name='assign_players_to_teams'),
    path('draft/simulate/', views.simulate_draft_view, name='simulate_draft'),
    path('reset-teams/', views.reset_teams_view, name='reset_teams'),
    path('api/import-players/', views.import_players_view, name='import_players'),
    path('players/', views.players_list_view, name='list'),
    path('players/create/', views.player_create_view, name='create'),
    path('players/<int:pk>/', views.player_detail_view, name='detail'),
    path('players/<int:pk>/delete/', views.player_delete_view, name='delete'),
    path('players/<int:pk>/assign-team/', views.assign_player_team_view, name='assign_team'),
    path('teams/', views.teams_list_view, name='teams_list'),
    path('teams/create/', views.team_create_view, name='team_create'),
    path('teams/<int:pk>/', views.team_edit_view, name='team_edit'),
    path('teams/<int:pk>/delete/', views.team_delete_view, name='team_delete'),
    path('teams/<str:team_secret>/', views.team_detail_view, name='team_detail'),
    path('managers/', views.managers_list_view, name='managers_list'),
    path('managers/create/', views.manager_create_view, name='manager_create'),
    path('managers/<int:pk>/', views.manager_detail_view, name='manager_detail'),
    path('managers/<int:pk>/delete/', views.manager_delete_view, name='manager_delete'),
    path('managers/<int:pk>/assign-team/', views.assign_manager_team_view, name='assign_manager_team'),
    path('managers/unassign-all/', views.unassign_all_managers_view, name='unassign_all_managers'),
    path('player_rankings/', views.player_rankings_view, name='player_rankings'),
    path('manager_daughter_rankings/', views.manager_daughter_rankings_view, name='manager_daughter_rankings'),
    path('team_preferences/', views.team_preferences_view, name='team_preferences'),
    path('team_preferences/save/', views.save_team_preferences_view, name='save_team_preferences'),
    path('team_preferences/analyze/', views.team_preferences_analyze_view, name='team_preferences_analyze'),
    path('team_preferences/run-analysis/', views.run_team_analysis_view, name='run_team_analysis'),
    path('team_preferences/assign/', views.assign_managers_to_teams_view, name='assign_managers_to_teams'),
    path('team_preferences/get-manager-emails/', views.get_manager_emails_view, name='get_manager_emails'),
    path('team_preferences/send-email/', views.send_team_preferences_email_view, name='send_team_preferences_email'),
    path('manage_practice_slots/', views.manage_practice_slots_view, name='manage_practice_slots'),
    path('practice_slots/create/', views.create_practice_slot_view, name='create_practice_slot'),
    path('practice_slots/<int:pk>/update/', views.update_practice_slot_view, name='update_practice_slot'),
    path('practice_slots/<int:pk>/delete/', views.delete_practice_slot_view, name='delete_practice_slot'),
]
