# Generated by Django 4.2.27 on 2025-12-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('history', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('conflict', models.TextField(blank=True, null=True)),
                ('additional_registration_info', models.TextField(blank=True, null=True)),
                ('parent_phone_1', models.CharField(max_length=20)),
                ('parent_email_1', models.EmailField(max_length=254)),
                ('parent_phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('jersey_size', models.CharField(blank=True, max_length=10, null=True)),
                ('manager_volunteer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assistant_manager_volunteer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
