# Generated by Django 4.2.26 on 2025-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
