# Generated by Django 4.2.27 on 2025-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_jersey_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
