# Generated by Django 4.2.26 on 2025-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_team_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField()),
                ('status', models.TextField()),
                ('draft_date', models.DateField()),
                ('picks_per_round', models.IntegerField()),
                ('public_url_secret', models.CharField(max_length=100)),
                ('order', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'draft',
                'ordering': ['-draft_date'],
            },
        ),
    ]
