# Generated by Django 4.2.26 on 2025-12-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_playerranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='players.manager'),
        ),
    ]
