# Generated by Django 4.2.26 on 2025-12-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_playerranking_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDaughterRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter_rankings', to='players.manager')),
            ],
            options={
                'db_table': 'manager_daughter_rankings',
            },
        ),
    ]
