# Generated by Django 4.2.26 on 2025-12-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_draftpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='practice_slot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
