# Generated by Django 4.2.26 on 2025-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_team_practice_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attended_try_out',
            field=models.BooleanField(default=True),
        ),
    ]
