# Generated by Django 4.2.26 on 2025-12-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_player_attended_try_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draftable',
            field=models.BooleanField(default=True),
        ),
    ]
