# Generated by Django 4.2.26 on 2025-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player_draftable'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='final_round_draft_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
