# Generated by Django 4.2.26 on 2025-12-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_draft_final_round_draft_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='public_url_secret',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='status',
        ),
    ]
