# Generated by Django 4.2.26 on 2025-12-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_remove_draft_public_url_secret_remove_draft_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='draft',
            name='draft_date',
        ),
    ]
