# Generated by Django 4.2.26 on 2025-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_alter_draft_options_remove_draft_draft_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='player_assigned_to_team',
            field=models.BooleanField(default=False),
        ),
    ]
