# Generated by Django 4.2.26 on 2025-12-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_draftpick_player_assigned_to_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_preferences', to='players.manager')),
            ],
            options={
                'db_table': 'team_preferences',
            },
        ),
    ]
