# Generated by Django 4.2.26 on 2025-12-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_teampreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_slot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_slots', to='players.team')),
            ],
            options={
                'db_table': 'practice_slots',
            },
        ),
    ]
