# Generated by Django 4.2.26 on 2025-12-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_practiceslot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='practiceslot',
            table='available_practice_slots',
        ),
    ]
