# Generated by Django 4.2.26 on 2025-12-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_alter_practiceslot_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceslot',
            name='team',
        ),
    ]
