# Generated by Django 4.2.26 on 2025-12-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_remove_practiceslot_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceslot',
            options={'verbose_name': 'Practice Slot', 'verbose_name_plural': 'Practice Slots'},
        ),
        migrations.AlterModelTable(
            name='practiceslot',
            table='practice_slots',
        ),
    ]
