# Generated by Django 4.2.26 on 2025-12-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_rename_practice_slots_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSlotRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_slot_rankings', to='players.team')),
            ],
            options={
                'verbose_name': 'Practice Slot Ranking',
                'verbose_name_plural': 'Practice Slot Rankings',
                'db_table': 'practice_slot_rankings',
            },
        ),
    ]
