# Generated by Django 4.2.26 on 2025-12-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_create_practice_slot_rankings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='practice_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='players.practiceslot'),
        ),
    ]
