# Generated by Django 4.2.26 on 2025-12-08 22:54

from django.db import migrations, models
import django.db.models.deletion


def clear_practice_slots(apps, schema_editor):
    """Clear all practice_slot values before changing field type"""
    Team = apps.get_model('players', 'Team')
    Team.objects.all().update(practice_slot=None)


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_create_practice_slot_rankings'),
    ]

    operations = [
        migrations.RunPython(clear_practice_slots, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='practice_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='players.practiceslot'),
        ),
    ]
