# Generated by Django 4.2.26 on 2025-12-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_generalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredDraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by_teams', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_players', to='players.team')),
            ],
            options={
                'verbose_name': 'Starred Draft Pick',
                'verbose_name_plural': 'Starred Draft Picks',
                'db_table': 'starred_draft_picks',
                'unique_together': {('player', 'team')},
            },
        ),
    ]
