# Generated by Django 4.2.27 on 2025-12-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_starreddraftpick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager_secret',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
