# Generated by Django 4.2.27 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_alter_team_manager_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='colors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
