# Generated by Django 4.2.27 on 2025-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_alter_team_manager_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationcode',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
