# Generated by Django 4.2.27 on 2026-01-05 18:49

from django.db import migrations


def add_sendgrid_sandbox_setting(apps, schema_editor):
    """Add enable_sendgrid_sandbox_mode setting to GeneralSettings"""
    GeneralSetting = apps.get_model('players', 'GeneralSetting')

    # Create the setting if it doesn't exist
    GeneralSetting.objects.get_or_create(
        key='enable_sendgrid_sandbox_mode',
        defaults={'value': 'false'}
    )


def reverse_sendgrid_sandbox_setting(apps, schema_editor):
    """Remove enable_sendgrid_sandbox_mode setting"""
    GeneralSetting = apps.get_model('players', 'GeneralSetting')
    GeneralSetting.objects.filter(key='enable_sendgrid_sandbox_mode').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_add_comments_to_manager'),
    ]

    operations = [
        migrations.RunPython(add_sendgrid_sandbox_setting, reverse_sendgrid_sandbox_setting),
    ]
