# Generated by Django 4.2.27 on 2026-01-05 18:58

from django.db import migrations


def add_sandbox_test_email_setting(apps, schema_editor):
    """Add sendgrid_sandbox_test_email setting to GeneralSettings"""
    GeneralSetting = apps.get_model('players', 'GeneralSetting')

    # Create the setting if it doesn't exist
    GeneralSetting.objects.get_or_create(
        key='sendgrid_sandbox_test_email',
        defaults={'value': ''}
    )


def reverse_sandbox_test_email_setting(apps, schema_editor):
    """Remove sendgrid_sandbox_test_email setting"""
    GeneralSetting = apps.get_model('players', 'GeneralSetting')
    GeneralSetting.objects.filter(key='sendgrid_sandbox_test_email').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_add_sendgrid_sandbox_setting'),
    ]

    operations = [
        migrations.RunPython(add_sandbox_test_email_setting, reverse_sandbox_test_email_setting),
    ]
