# Generated by Django 4.2.27 on 2026-01-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0050_add_final_round_picks_to_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starreddraftpick',
            options={'ordering': ['team', 'order'], 'verbose_name': 'Starred Draft Pick', 'verbose_name_plural': 'Starred Draft Picks'},
        ),
        migrations.AddField(
            model_name='starreddraftpick',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
