# Generated by Django 4.2.27 on 2026-01-14 17:08

from django.db import migrations, models


def create_quick_links(apps, schema_editor):
    """Create quick links table and populate with initial data"""
    QuickLink = apps.get_model('players', 'QuickLink')

    # Only create links if none exist
    if QuickLink.objects.count() == 0:
        links_data = [
            {
                'name': 'Submit Team Preferences',
                'url': '/players/team_preferences/',
                'icon': 'bi-clipboard-check',
                'display_order': 1
            },
            {
                'name': 'Manager Data',
                'url': '#',
                'icon': 'bi-people-fill',
                'display_order': 2
            },
            {
                'name': 'Pre-Season Info Deck',
                'url': 'https://docs.google.com/presentation/d/1NdUP0QAdI8vp_TmofHwIEyrsXc5GKPEP8b_yEoDk1VQ/edit?usp=sharing',
                'icon': 'bi-file-earmark-slides',
                'display_order': 3
            },
            {
                'name': 'Player Data & Eval Template',
                'url': 'https://docs.google.com/spreadsheets/d/1eo7L0w6liR51sMMBjkwuxvdPCPKYLsFR/edit?usp=sharing&ouid=106177974752139787465&rtpof=true&sd=true',
                'icon': 'bi-table',
                'display_order': 4
            },
            {
                'name': 'Try Out Registrations',
                'url': 'https://docs.google.com/spreadsheets/d/1Kdw5pIWtB9i2cjqwVGx6Iry5fJgojsUj/edit?usp=sharing&ouid=106177974752139787465&rtpof=true&sd=true',
                'icon': 'bi-clipboard-data',
                'display_order': 5
            },
            {
                'name': 'WUSA Field Locations',
                'url': 'https://www.wusa.org/locations',
                'icon': 'bi-geo-alt',
                'display_order': 6
            }
        ]

        for link_data in links_data:
            QuickLink.objects.create(**link_data)


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0053_divisionvalidationregistry_quicklink_validationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'db_table': 'quick_links',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(create_quick_links),
    ]
