# Generated by Django 4.2.27 on 2026-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0054_create_quicklink_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
