# Generated by Django 4.2.27 on 2026-01-14 19:00

from django.db import migrations, models


def create_fixed_quick_links(apps, schema_editor):
    """Create or update fixed quick links"""
    QuickLink = apps.get_model('players', 'QuickLink')

    # Create or update "All Division Players" link
    all_players_link, created = QuickLink.objects.get_or_create(
        name='All Division Players',
        defaults={
            'url': '#all-division-players',
            'icon': 'bi-people-fill',
            'display_order': 0,
            'is_active': True,
            'is_fixed': True
        }
    )
    if not created:
        all_players_link.url = '#all-division-players'
        all_players_link.icon = 'bi-people-fill'
        all_players_link.display_order = 0
        all_players_link.is_active = True
        all_players_link.is_fixed = True
        all_players_link.save()

    # Update existing "Manager Data" link to be fixed
    try:
        manager_data_link = QuickLink.objects.get(name='Manager Data')
        manager_data_link.url = '#manager-contact-info'
        manager_data_link.display_order = 1
        manager_data_link.is_fixed = True
        manager_data_link.save()
    except QuickLink.DoesNotExist:
        # Create if it doesn't exist
        QuickLink.objects.create(
            name='Manager Data',
            url='#manager-contact-info',
            icon='bi-person-lines-fill',
            display_order=1,
            is_active=True,
            is_fixed=True
        )

    # Update display_order for all other links to be >= 2
    other_links = QuickLink.objects.filter(is_fixed=False).order_by('display_order')
    for index, link in enumerate(other_links, start=2):
        if link.display_order < 2:
            link.display_order = index
            link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0055_add_is_active_to_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_fixed_quick_links, migrations.RunPython.noop),
    ]
