# Generated by Django 4.2.27 on 2026-01-14

from django.db import migrations


def add_visibility_settings(apps, schema_editor):
    """Add initial visibility settings for component categories"""
    GeneralSetting = apps.get_model('players', 'GeneralSetting')

    # Create visibility settings - all visible by default
    GeneralSetting.objects.get_or_create(
        key='show_preseason_items',
        defaults={'value': 'true'}
    )

    GeneralSetting.objects.get_or_create(
        key='show_testing_items',
        defaults={'value': 'true'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0056_add_is_fixed_to_quicklink'),
    ]

    operations = [
        migrations.RunPython(add_visibility_settings, migrations.RunPython.noop),
    ]
