# Generated by Django 4.2.27 on 2026-01-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0057_add_component_visibility_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('clearance_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_checks', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='players.team')),
            ],
            options={
                'verbose_name': 'Background Check',
                'verbose_name_plural': 'Background Checks',
                'db_table': 'background_checks',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
