# Generated by Django 4.2.27 on 2026-01-14 20:49

from django.db import migrations, models
import django.db.models.deletion


def delete_records_with_null_player(apps, schema_editor):
    """Delete any background check records that have a null player"""
    BackgroundCheck = apps.get_model('players', 'BackgroundCheck')
    BackgroundCheck.objects.filter(player__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0058_backgroundcheck'),
    ]

    operations = [
        # First, delete any records with null player (shouldn't be any)
        migrations.RunPython(delete_records_with_null_player, migrations.RunPython.noop),
        # Then alter the field to be non-nullable
        migrations.AlterField(
            model_name='backgroundcheck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='players.player'),
        ),
    ]
