# Generated by Django 4.2.27 on 2026-01-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0060_event_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_1', models.JSONField(default=dict, help_text='Field positions for inning 1')),
                ('inning_2', models.JSONField(default=dict, help_text='Field positions for inning 2')),
                ('inning_3', models.JSONField(default=dict, help_text='Field positions for inning 3')),
                ('inning_4', models.JSONField(default=dict, help_text='Field positions for inning 4')),
                ('inning_5', models.JSONField(default=dict, help_text='Field positions for inning 5')),
                ('inning_6', models.JSONField(default=dict, help_text='Field positions for inning 6')),
                ('lineup', models.JSONField(default=list, help_text='Batting lineup order')),
                ('validation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='players.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='players.team')),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Rosters',
                'db_table': 'rosters',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'team')},
            },
        ),
    ]
