# Generated by Django 4.2.27 on 2026-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0061_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='inning_1',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 1', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='inning_2',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 2', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='inning_3',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 3', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='inning_4',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 4', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='inning_5',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 5', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='inning_6',
            field=models.JSONField(blank=True, default=dict, help_text='Field positions for inning 6', null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='lineup',
            field=models.JSONField(blank=True, default=list, help_text='Batting lineup order', null=True),
        ),
    ]
